import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const IMAGES_ROOT = path.join(ROOT, "public", "images", "projects");
const VIDEOS_ROOT = path.join(ROOT, "public", "videos", "projects");
const OUTPUT = path.join(ROOT, "src", "data", "projectMedia.generated.ts");

const IMAGE_EXTS = new Set([".png", ".jpg", ".jpeg", ".webp", ".gif", ".avif"]);
const VIDEO_EXTS = new Set([".mp4", ".webm", ".mov", ".m4v"]);

const listDirs = (p) => {
  try {
    return fs
      .readdirSync(p, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name);
  } catch {
    return [];
  }
};

const listFiles = (p) => {
  try {
    return fs
      .readdirSync(p, { withFileTypes: true })
      .filter((d) => d.isFile())
      .map((d) => d.name);
  } catch {
    return [];
  }
};

const scanSlug = (slug) => {
  const imgs = listFiles(path.join(IMAGES_ROOT, slug));
  const vids = listFiles(path.join(VIDEOS_ROOT, slug));

  let cover;
  const numbered = [];
  for (const f of imgs) {
    const ext = path.extname(f).toLowerCase();
    if (!IMAGE_EXTS.has(ext)) continue;
    const base = path.basename(f, ext);
    const src = `/images/projects/${slug}/${f}`;
    if (base === "cover") cover = src;
    else if (/^\d+$/.test(base)) numbered.push({ n: parseInt(base, 10), src });
  }
  numbered.sort((a, b) => a.n - b.n);
  const screenshots = numbered.map((x) => x.src);

  let demoVideo;
  const numberedVideos = [];
  for (const f of vids) {
    const ext = path.extname(f).toLowerCase();
    if (!VIDEO_EXTS.has(ext)) continue;
    const base = path.basename(f, ext);
    const src = `/videos/projects/${slug}/${f}`;
    if (base === "demo") demoVideo = src;
    else if (/^\d+$/.test(base)) numberedVideos.push({ n: parseInt(base, 10), src });
  }
  numberedVideos.sort((a, b) => a.n - b.n);
  const videos = [
    ...(demoVideo ? [demoVideo] : []),
    ...numberedVideos.map((x) => x.src),
  ];

  return { cover, screenshots, videos };
};

const slugs = new Set([...listDirs(IMAGES_ROOT), ...listDirs(VIDEOS_ROOT)]);
const media = {};
for (const slug of [...slugs].sort()) {
  const m = scanSlug(slug);
  if (m.cover || m.screenshots.length || m.videos.length) media[slug] = m;
}

const out =
  `// AUTO-GENERATED by scripts/generateProjectMedia.mjs. Do not edit.\n` +
  `// Re-runs on \`npm run dev\` and \`npm run build\`.\n\n` +
  `export interface ProjectMedia {\n` +
  `  cover?: string;\n` +
  `  screenshots: string[];\n` +
  `  videos: string[];\n` +
  `}\n\n` +
  `export const projectMedia: Record<string, ProjectMedia> = ${JSON.stringify(
    media,
    null,
    2,
  )};\n`;

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, out);
console.log(
  `[generateProjectMedia] wrote ${path.relative(ROOT, OUTPUT)} (${Object.keys(media).length} project${Object.keys(media).length === 1 ? "" : "s"})`,
);
