// AUTO-GENERATED by scripts/generateProjectMedia.mjs. Do not edit.
// Re-runs on `npm run dev` and `npm run build`.

export interface ProjectMedia {
  cover?: string;
  screenshots: string[];
  videos: string[];
}

export const projectMedia: Record<string, ProjectMedia> = {
  "baja-solutions": {
    "cover": "/images/projects/baja-solutions/cover.png",
    "screenshots": [
      "/images/projects/baja-solutions/1.png",
      "/images/projects/baja-solutions/2.png",
      "/images/projects/baja-solutions/3.png"
    ],
    "videos": [
      "/videos/projects/baja-solutions/1.mp4"
    ]
  },
  "borderpulse": {
    "cover": "/images/projects/borderpulse/cover.png",
    "screenshots": [
      "/images/projects/borderpulse/1.png",
      "/images/projects/borderpulse/2.png"
    ],
    "videos": [
      "/videos/projects/borderpulse/1.mp4"
    ]
  },
  "borderpulse-mobile": {
    "cover": "/images/projects/borderpulse-mobile/cover.png",
    "screenshots": [
      "/images/projects/borderpulse-mobile/1.png"
    ],
    "videos": [
      "/videos/projects/borderpulse-mobile/1.mp4"
    ]
  },
  "bracabudget": {
    "cover": "/images/projects/bracabudget/cover.png",
    "screenshots": [
      "/images/projects/bracabudget/1.png",
      "/images/projects/bracabudget/2.png"
    ],
    "videos": [
      "/videos/projects/bracabudget/1.mp4",
      "/videos/projects/bracabudget/2.mp4"
    ]
  },
  "cmdgui": {
    "cover": "/images/projects/cmdgui/cover.png",
    "screenshots": [
      "/images/projects/cmdgui/1.png",
      "/images/projects/cmdgui/2.png",
      "/images/projects/cmdgui/3.png"
    ],
    "videos": []
  },
  "homelab": {
    "cover": "/images/projects/homelab/cover.png",
    "screenshots": [
      "/images/projects/homelab/2.png",
      "/images/projects/homelab/3.png"
    ],
    "videos": []
  },
  "simpleports": {
    "cover": "/images/projects/simpleports/cover.png",
    "screenshots": [],
    "videos": []
  }
};
